### ISSUE TITLE
Building RPM

### ISSUE THREAD

**Issue by andrew-statsenko** [igorcoding/EV-Tarantool16#11]
Igor, if you have some time it will be great if you provide ability for build RPM. Looks like .spec exists, but I don't know where.

Thank you !

**Comment by igorcoding** [comment]
Hi! I've added an RPM spec to build EV::Tarantool16 (https://github.com/igorcoding/EV-Tarantool16/blob/master/rpm/perl-EV-Tarantool16.spec) and also set up the packaging deployment to packagecloud if you want to get already built packages for centos:7 - https://packagecloud.io/igorcoding/tarantoolcontrib
